### ISSUE TITLE
Could upgrade the `near-sandbox` NPM to the latest from `nearcore`

### ISSUE THREAD

**Issue by fadeevab** [near/sandbox#27]
Hi folks!

Could you upgrade the sandbox binary to the latest one from the `nearcore`?
**Problem:** I use sandbox for integration tests and some contract calls exceed 300TGas (the same methods consume just 25 TGas at the real testnet).
```
     Error: {"index":0,"kind":{"ExecutionError":"Exceeded the prepaid gas."}}
      at Object.parseResultError (node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
      at Account.signAndSendTransactionV2 (node_modules/near-api-js/lib/account.js:160:36)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Contract._changeMethod (node_modules/near-api-js/lib/contract.js:102:27)
      at async Context.<anonymous> (tests/tests.js:211:18)
```
**Root of cause**: the current version of sandbox consumes more gas than the latest sandbox, and unfortunately the near-sandbox burns 10x gas compared to the real mainnet/testnet deployment which is another issue.
**Measure**: Rebuild the near-sandbox binary from the latest `nearcore` and publish. It fixes my issue.

Thank you!

**Comment by willemneal** [comment]
Just update this url.  
 ​   ​`https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/​${​platform​}​-​${​arch​}​/master/2c9375ee5ee307c2ce870c7dbd25eefd84fe8c36/near-sandbox.tar.gz`​;

It should allow a version # where the commit hash is.

I wanted to have a github action to automatically publish with nearcore. Feel free to make a PR to update to the most recent nearcore version. I'll review it but can't merge.

**Comment by fadeevab** [comment]
@willemneal I use it like this:
`package.json`:
```json
  "devDependencies": {
    "near-sandbox": "^0.0.8",
  }
```
Then I run the following command (in my GitHub actions):
```bash
npm install
```
`near-sandbox/dist/getBinary.js` already contains this URL: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/${platform}-${arch}/master/2c9375ee5ee307c2ce870c7dbd25eefd84fe8c36/near-sandbox.tar.gz. I assume you should replace the `near-sandbox.tar.gz` with the latest version built from `nearcore`. (?)

**Comment by fadeevab** [comment]
Ideally, I believe, it's better to publish `near-sandbox` `0.0.9` with the path on the newest `near-sandbox.tar.gz`.

**Comment by willemneal** [comment]
My point was you could make a PR to update to the latest.  Currently the commit on master for nearcore is `7fe512457695f91717ab23e4c3ec34c26a87ed75`.  So you could update that line and make a PR.  I just made a PR to nearcore: https://github.com/near/nearcore/pull/6426, which willl you change that the link from `master/.../near-sandbox.tar.gz` to `1.24.0/sandbox.tar.gz`. Perhaps for now a PR to allow an ENV var to override the current one would be a good one. E.g.

`https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/​${​platform​}​-​${​arch​}​/master/2c9375ee5ee307c2ce870c7dbd25eefd84fe8c36/near-sandbox.tar.gz` --> `https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/​${​platform​}​-​${​arch​}​/${current_version()}/near-sandbox.tar.gz`, where `current_version()` will check an env otherwise default.

**Comment by fadeevab** [comment]
@willemneal Something like this? https://github.com/near/sandbox/pull/28

I've tested the binary by a local fix, it's been downloaded and it works.

**Comment by fadeevab** [comment]
Resolved here: https://github.com/near/sandbox/pull/33
